### ISSUE TITLE
Does not work / Breaks liveries with non in-line countries in description.lua

### ISSUE THREAD

**Issue by JacobyWitness** [LombardiDaniel/dcs-livery-unlocker#1]
The program automatically comments out the line "countries = {" which works on most lua files, but on some the country names are in another line below that, which ends up breaking the livery so that it cant be chosen in-game at all.
Examples:
![image](https://user-images.githubusercontent.com/98648759/154371579-f42e0cac-c5ed-495c-a503-a939a9072ee8.png)
Here you can see where the country abbreviation is not inline with the commented out line the unlocker changes.
![image](https://user-images.githubusercontent.com/98648759/154371598-3d6d6523-ee25-418f-8572-2d4187764007.png)
Example where it works as intended

The way to fix this it seems is to look for the closing curly bracket and either delete or comment out anything between. As long as the last bracket is there it wont work.

**Comment by LombardiDaniel** [comment]
Hm...Didn't even imagine that could happen, thank you for the heads up. I'll try fix it this week. Then I'll get back to you. Thanks for the attention!

**Comment by LombardiDaniel** [comment]
Thank you @JacobyWitness again for bringing this issue up. It is now fixed. I am closing the issue.
